/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
To view the source, visit the GitHub repository of this plugin.
*/
"use strict";
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AppleJournalImporterPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  targetFolder: "Journal",
  convertHeic: true,
  mediaSubfolder: "media"
};

// src/ui/ImportModal.ts
var import_obsidian2 = require("obsidian");

// src/importer.ts
var import_obsidian = require("obsidian");
var fs = __toESM(require("fs"));
var fsp = __toESM(require("fs/promises"));
var path = __toESM(require("path"));
var import_child_process = require("child_process");
var import_util = require("util");

// src/parser.ts
function parseEntryFilename(filename) {
  var _a;
  const base = filename.replace(/\.html$/i, "");
  const m = base.match(/^(\d{4}-\d{2}-\d{2})(?:_(.+))?$/);
  if (!m) {
    return { date: "", titleFromFilename: base, duplicateSuffix: void 0 };
  }
  const date = m[1];
  const rest = (_a = m[2]) != null ? _a : "";
  const dupMatch = rest.match(/^\((\d+)\)$/);
  if (dupMatch) {
    const n = parseInt(dupMatch[1], 10) + 1;
    return { date, titleFromFilename: "", duplicateSuffix: `(${n})` };
  }
  const titleFromFilename = rest.replace(/_/g, " ").trim();
  return { date, titleFromFilename, duplicateSuffix: void 0 };
}
function classToAssetType(className) {
  if (className.includes("assetType_photo")) return "photo";
  if (className.includes("assetType_video")) return "video";
  if (className.includes("assetType_audio")) return "audio";
  if (className.includes("assetType_multiPinMap")) return "map";
  if (className.includes("assetType_stateOfMind")) return "stateOfMind";
  if (className.includes("assetType_motionActivity")) return "motionActivity";
  if (className.includes("assetType_workoutIcon")) return "workoutIcon";
  if (className.includes("assetType_contact")) return "contact";
  return "unknown";
}
function extractAssets(assetGrid) {
  var _a, _b, _c, _d, _e, _f, _g;
  const assets = [];
  for (const item of Array.from(assetGrid.querySelectorAll(".gridItem"))) {
    const uuid = (_a = item.id) != null ? _a : "";
    const type = classToAssetType(item.className);
    const img = item.querySelector("img");
    const videoSrc = item.querySelector("video source");
    const audioSrc = item.querySelector("audio source");
    const mediaEl = (_b = img != null ? img : videoSrc) != null ? _b : audioSrc;
    const rawSrc = (_c = mediaEl == null ? void 0 : mediaEl.getAttribute("src")) != null ? _c : "";
    const filename = rawSrc.replace(/^\.\.\/Resources\//, "").replace(/^Resources\//, "");
    const overlayText = ((_e = (_d = item.querySelector(".gridItemOverlayFooter")) == null ? void 0 : _d.textContent) == null ? void 0 : _e.trim()) || void 0;
    const duration = ((_g = (_f = item.querySelector(".durationText")) == null ? void 0 : _f.textContent) == null ? void 0 : _g.trim()) || void 0;
    if (uuid || filename) {
      assets.push({ uuid, type, filename, overlayText, duration });
    }
  }
  return assets;
}
function extractBodyLines(bodyEl) {
  const lines = [];
  function walk(el) {
    var _a, _b, _c, _d;
    const tag = el.tagName.toLowerCase();
    if (tag === "ul" || tag === "ol") {
      for (const li of Array.from(el.querySelectorAll(":scope > li"))) {
        const text = (_b = (_a = li.textContent) == null ? void 0 : _a.trim()) != null ? _b : "";
        if (text) lines.push(`- ${text}`);
      }
      return;
    }
    if (tag === "p" || tag === "div") {
      const childTags = Array.from(el.children).map(
        (c) => c.tagName.toLowerCase()
      );
      const hasBlockChildren = childTags.some(
        (t) => ["p", "div", "ul", "ol", "li"].includes(t)
      );
      if (!hasBlockChildren) {
        const text = (_d = (_c = el.textContent) == null ? void 0 : _c.trim()) != null ? _d : "";
        if (text) lines.push(text);
        return;
      }
    }
    for (const child of Array.from(el.children)) {
      walk(child);
    }
  }
  walk(bodyEl);
  return lines.filter((line, i, arr) => {
    if (line !== "") return true;
    return i > 0 && arr[i - 1] !== "";
  });
}
function parseHtmlEntry(htmlContent, sourcePath, filename) {
  var _a, _b, _c;
  const { date, titleFromFilename, duplicateSuffix } = parseEntryFilename(filename);
  const parser = new DOMParser();
  const doc = parser.parseFromString(htmlContent, "text/html");
  const htmlTitle = (_c = (_b = (_a = doc.querySelector(".title")) == null ? void 0 : _a.textContent) == null ? void 0 : _b.trim()) != null ? _c : "";
  const title = htmlTitle || titleFromFilename;
  const assetGrid = doc.querySelector(".assetGrid");
  const assets = assetGrid ? extractAssets(assetGrid) : [];
  const bodyEl = doc.querySelector(".bodyText");
  const bodyLines = bodyEl ? extractBodyLines(bodyEl) : [];
  return { date, title, assets, bodyLines, sourcePath, duplicateSuffix };
}

// src/converter.ts
function assetToMarkdown(asset, mediaSubfolder) {
  const raw = asset.filename;
  if (!raw) return assetFallback(asset);
  const displayName = raw.replace(/\.heic$/i, ".jpg");
  const embedPath = `${mediaSubfolder}/${displayName}`;
  switch (asset.type) {
    case "photo":
      return `![[${embedPath}]]`;
    case "video":
      return `![[${embedPath}]]`;
    case "audio":
      return `![[${embedPath}]]`;
    case "map": {
      const img = `![[${embedPath}]]`;
      return asset.overlayText ? `\u{1F4CD} ${asset.overlayText}
${img}` : img;
    }
    default:
      return assetFallback(asset);
  }
}
function assetFallback(asset) {
  switch (asset.type) {
    case "stateOfMind":
      return "\u{1F9E0} State of mind";
    case "motionActivity":
      return "\u{1F3C3} Activity recorded";
    case "workoutIcon":
      return "\u{1F4AA} Workout";
    case "contact":
      return "\u{1F464} Contact";
    default:
      return "";
  }
}
function entryToMarkdown(entry, mediaSubfolder) {
  const lines = [];
  lines.push("---");
  lines.push(`date: ${entry.date}`);
  if (entry.title) {
    lines.push(`title: "${entry.title.replace(/"/g, '\\"')}"`);
  }
  lines.push("tags:");
  lines.push("  - journal");
  lines.push("---");
  lines.push("");
  for (const asset of entry.assets) {
    const md = assetToMarkdown(asset, mediaSubfolder);
    if (md) {
      lines.push(md);
      lines.push("");
    }
  }
  if (entry.bodyLines.length > 0) {
    lines.push(...entry.bodyLines);
    lines.push("");
  }
  return lines.join("\n");
}

// src/importer.ts
var execFileAsync = (0, import_util.promisify)(import_child_process.execFile);
function sanitiseName(name) {
  return name.replace(/[\\/:*?"<>|#^[\]]/g, "-").trim();
}
function vaultBasePath(app) {
  return app.vault.adapter.getBasePath();
}
async function ensureVaultFolder(app, vaultPath) {
  if (!app.vault.getAbstractFileByPath(vaultPath)) {
    await app.vault.createFolder(vaultPath);
  }
}
async function writeNote(app, vaultPath, content) {
  const existing = app.vault.getAbstractFileByPath(vaultPath);
  if (existing instanceof import_obsidian.TFile) {
    await app.vault.modify(existing, content);
  } else {
    await app.vault.create(vaultPath, content);
  }
}
async function copyMedia(srcPath, destAbsPath, convertHeic) {
  if (fs.existsSync(destAbsPath)) return;
  const ext = path.extname(srcPath).toLowerCase();
  if (ext === ".heic" && convertHeic) {
    await execFileAsync("sips", [
      "-s",
      "format",
      "jpeg",
      srcPath,
      "--out",
      destAbsPath
    ]);
  } else {
    await fsp.copyFile(srcPath, destAbsPath);
  }
}
async function processAssets(assets, resourcesDir, mediaFolderAbsPath, convertHeic) {
  await fsp.mkdir(mediaFolderAbsPath, { recursive: true });
  for (const asset of assets) {
    if (!asset.filename) continue;
    const srcPath = path.join(resourcesDir, asset.filename);
    if (!fs.existsSync(srcPath)) continue;
    const ext = path.extname(asset.filename).toLowerCase();
    const destFilename = ext === ".heic" && convertHeic ? asset.filename.replace(/\.heic$/i, ".jpg") : asset.filename;
    const destAbsPath = path.join(mediaFolderAbsPath, destFilename);
    try {
      await copyMedia(srcPath, destAbsPath, convertHeic);
    } catch (e) {
      if (!fs.existsSync(destAbsPath)) {
        await fsp.copyFile(srcPath, destAbsPath);
      }
    }
  }
}
function resolveEntryPaths(entry, targetFolder, mediaSubfolder) {
  const date = entry.date || "unknown";
  const dayFolder = (0, import_obsidian.normalizePath)(`${targetFolder}/${sanitiseName(date)}`);
  let noteBaseName;
  if (entry.duplicateSuffix) {
    noteBaseName = `${date} ${entry.duplicateSuffix}`;
  } else if (entry.title) {
    noteBaseName = `${date} - ${sanitiseName(entry.title)}`;
  } else {
    noteBaseName = date;
  }
  const noteFile = (0, import_obsidian.normalizePath)(`${dayFolder}/${noteBaseName}.md`);
  const mediaFolder = (0, import_obsidian.normalizePath)(`${dayFolder}/${mediaSubfolder}`);
  return { dayFolder, noteFile, mediaFolder };
}
async function runImport(app, settings, exportPath, onProgress) {
  const entriesDir = path.join(exportPath, "Entries");
  const resourcesDir = path.join(exportPath, "Resources");
  const htmlFiles = fs.readdirSync(entriesDir).filter((f) => f.toLowerCase().endsWith(".html")).sort();
  const result = {
    total: htmlFiles.length,
    imported: 0,
    skipped: 0,
    errors: []
  };
  await ensureVaultFolder(app, settings.targetFolder);
  const basePath = vaultBasePath(app);
  for (let i = 0; i < htmlFiles.length; i++) {
    const filename = htmlFiles[i];
    onProgress(i + 1, htmlFiles.length, filename);
    try {
      const htmlPath = path.join(entriesDir, filename);
      const htmlContent = await fsp.readFile(htmlPath, "utf-8");
      const entry = parseHtmlEntry(htmlContent, htmlPath, filename);
      const { dayFolder, noteFile, mediaFolder } = resolveEntryPaths(
        entry,
        settings.targetFolder,
        settings.mediaSubfolder
      );
      await ensureVaultFolder(app, dayFolder);
      if (entry.assets.some((a) => a.filename)) {
        const mediaFolderAbs = path.join(basePath, mediaFolder);
        await processAssets(
          entry.assets,
          resourcesDir,
          mediaFolderAbs,
          settings.convertHeic
        );
      }
      const markdown = entryToMarkdown(entry, settings.mediaSubfolder);
      await writeNote(app, noteFile, markdown);
      result.imported++;
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      result.errors.push({ entry: filename, error: message });
    }
  }
  return result;
}
function validateExportPath(exportPath) {
  if (!exportPath) return "Please enter the path to your Apple Journal export folder.";
  const trimmed = exportPath.trim();
  if (!fs.existsSync(trimmed)) return `Folder not found: ${trimmed}`;
  const entriesDir = path.join(trimmed, "Entries");
  const resourcesDir = path.join(trimmed, "Resources");
  if (!fs.existsSync(entriesDir))
    return `Could not find an Entries/ subfolder inside:
${trimmed}`;
  if (!fs.existsSync(resourcesDir))
    return `Could not find a Resources/ subfolder inside:
${trimmed}`;
  const count = fs.readdirSync(entriesDir).filter((f) => f.toLowerCase().endsWith(".html")).length;
  if (count === 0) return "No .html entry files found in the Entries/ folder.";
  return null;
}
function countEntries(exportPath) {
  const entriesDir = path.join(exportPath.trim(), "Entries");
  return fs.readdirSync(entriesDir).filter((f) => f.toLowerCase().endsWith(".html")).length;
}

// src/ui/ImportModal.ts
var ImportModal = class extends import_obsidian2.Modal {
  constructor(app, settings) {
    super(app);
    this.settings = settings;
    this.exportPath = "";
    this.modalEl.addClass("apple-journal-importer-modal");
  }
  onOpen() {
    this.renderPicker();
  }
  onClose() {
    this.contentEl.empty();
  }
  // ---------------------------------------------------------------------------
  // Step 1 — path picker
  // ---------------------------------------------------------------------------
  renderPicker() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Import Apple Journal" });
    contentEl.createEl("p", {
      text: "Point to the folder you exported from the Apple Journal app. It should contain an Entries/ and a Resources/ subfolder.",
      cls: "setting-item-description"
    });
    const pathSetting = new import_obsidian2.Setting(contentEl).setName("Export folder path").setClass("path-setting").addText((text) => {
      text.setPlaceholder("/Users/you/Downloads/AppleJournalEntries").setValue(this.exportPath).onChange((val) => {
        this.exportPath = val;
      });
      text.inputEl.style.width = "100%";
      text.inputEl.addEventListener("keydown", (e) => {
        if (e.key === "Enter") this.confirmPath();
      });
    });
    pathSetting.settingEl.style.flexDirection = "column";
    pathSetting.settingEl.style.alignItems = "stretch";
    new import_obsidian2.Setting(contentEl).addButton((btn) => {
      btn.setButtonText("Next \u2192").setCta().onClick(() => this.confirmPath());
    });
  }
  confirmPath() {
    const path2 = this.exportPath.trim();
    const error = validateExportPath(path2);
    if (error) {
      new import_obsidian2.Notice(error);
      return;
    }
    this.renderConfirm(path2);
  }
  // ---------------------------------------------------------------------------
  // Step 2 — confirm + start
  // ---------------------------------------------------------------------------
  renderConfirm(exportPath) {
    const { contentEl } = this;
    contentEl.empty();
    const count = countEntries(exportPath);
    contentEl.createEl("h2", { text: "Ready to import" });
    contentEl.createEl("p", {
      text: `Found ${count} journal entries.`
    });
    contentEl.createEl("p", {
      text: `They will be imported into "${this.settings.targetFolder}" in your vault.`,
      cls: "setting-item-description"
    });
    if (this.settings.convertHeic) {
      contentEl.createEl("p", {
        text: "HEIC images will be converted to JPEG (requires macOS).",
        cls: "setting-item-description"
      });
    }
    new import_obsidian2.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("\u2190 Back").onClick(() => this.renderPicker())
    ).addButton((btn) => {
      btn.setButtonText(`Import ${count} entries`).setCta().onClick(() => this.startImport(exportPath, count));
    });
  }
  // ---------------------------------------------------------------------------
  // Step 3 — progress
  // ---------------------------------------------------------------------------
  async startImport(exportPath, total) {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Importing\u2026" });
    const progressWrap = contentEl.createDiv({ cls: "progress-wrap" });
    const progressBar = progressWrap.createEl("progress");
    progressBar.max = total;
    progressBar.value = 0;
    const progressLabel = progressWrap.createDiv({
      cls: "progress-label",
      text: "Starting\u2026"
    });
    const result = await runImport(
      this.app,
      this.settings,
      exportPath,
      (current, _total, label) => {
        progressBar.value = current;
        progressLabel.setText(`${current} / ${_total} \u2014 ${label}`);
      }
    );
    this.renderSummary(result);
  }
  // ---------------------------------------------------------------------------
  // Step 4 — summary
  // ---------------------------------------------------------------------------
  renderSummary(result) {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Import complete" });
    const stats = contentEl.createDiv({ cls: "summary-stats" });
    this.createStat(stats, String(result.imported), "imported");
    if (result.skipped > 0) {
      this.createStat(stats, String(result.skipped), "skipped");
    }
    if (result.errors.length > 0) {
      this.createStat(stats, String(result.errors.length), "errors", true);
    }
    if (result.errors.length > 0) {
      contentEl.createEl("p", { text: "Errors:" });
      const log = contentEl.createDiv({ cls: "error-log" });
      for (const err of result.errors) {
        log.createEl("p", { text: `${err.entry}: ${err.error}` });
      }
    }
    new import_obsidian2.Setting(contentEl).addButton((btn) => {
      btn.setButtonText("Close").setCta().onClick(() => this.close());
    });
  }
  createStat(parent, value, label, isError = false) {
    const stat = parent.createDiv({ cls: "stat" });
    const valueEl = stat.createDiv({ cls: "stat-value", text: value });
    if (isError) valueEl.addClass("error");
    stat.createDiv({ cls: "stat-label", text: label });
  }
};

// src/ui/SettingsTab.ts
var import_obsidian3 = require("obsidian");
var SettingsTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Apple Journal Importer" });
    new import_obsidian3.Setting(containerEl).setName("Target folder").setDesc(
      "Vault folder where imported entries will be created. Will be created if it does not exist."
    ).addText((text) => {
      text.setPlaceholder("Journal").setValue(this.plugin.settings.targetFolder).onChange(async (val) => {
        this.plugin.settings.targetFolder = val.trim() || "Journal";
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian3.Setting(containerEl).setName("Convert HEIC to JPEG").setDesc(
      "Convert Apple HEIC images to JPEG so Obsidian can display them inline. Uses the built-in macOS sips command."
    ).addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.convertHeic).onChange(async (val) => {
        this.plugin.settings.convertHeic = val;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian3.Setting(containerEl).setName("Media subfolder name").setDesc(
      "Name of the subfolder inside each entry folder where media files are stored."
    ).addText((text) => {
      text.setPlaceholder("media").setValue(this.plugin.settings.mediaSubfolder).onChange(async (val) => {
        this.plugin.settings.mediaSubfolder = val.trim() || "media";
        await this.plugin.saveSettings();
      });
    });
  }
};

// src/main.ts
var AppleJournalImporterPlugin = class extends import_obsidian4.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new SettingsTab(this.app, this));
    this.addCommand({
      id: "import-apple-journal",
      name: "Import Apple Journal",
      callback: () => new ImportModal(this.app, this.settings).open()
    });
    this.addRibbonIcon("book-open", "Import Apple Journal", () => {
      new ImportModal(this.app, this.settings).open();
    });
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
