/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
To view the source, visit the GitHub repository of this plugin.
*/
"use strict";
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AppleJournalImporterPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  targetFolder: "Journal",
  convertHeic: true,
  mediaSubfolder: "media"
};
var CONVERTED_IMAGE_EXTS = /* @__PURE__ */ new Set([".heic", ".jpg", ".jpeg", ".png"]);

// src/ui/ImportModal.ts
var import_obsidian2 = require("obsidian");

// src/importer.ts
var import_obsidian = require("obsidian");
var fs = __toESM(require("fs"));
var fsp = __toESM(require("fs/promises"));
var path = __toESM(require("path"));
var import_child_process = require("child_process");
var import_util = require("util");

// src/parser.ts
function parseEntryFilename(filename) {
  var _a;
  const base = filename.replace(/\.html$/i, "");
  const m = base.match(/^(\d{4}-\d{2}-\d{2})(?:_(.+))?$/);
  if (!m) {
    return { date: "", titleFromFilename: base, duplicateSuffix: void 0 };
  }
  const date = m[1];
  const rest = (_a = m[2]) != null ? _a : "";
  const dupMatch = rest.match(/^\((\d+)\)$/);
  if (dupMatch) {
    const n = parseInt(dupMatch[1], 10) + 1;
    return { date, titleFromFilename: "", duplicateSuffix: `(${n})` };
  }
  const titleFromFilename = rest.replace(/_/g, " ").trim();
  return { date, titleFromFilename, duplicateSuffix: void 0 };
}
function classToAssetType(className) {
  if (className.includes("assetType_photo")) return "photo";
  if (className.includes("assetType_livePhoto")) return "photo";
  if (className.includes("assetType_video")) return "video";
  if (className.includes("assetType_audio")) return "audio";
  if (className.includes("assetType_music")) return "music";
  if (className.includes("assetType_multiPinMap")) return "map";
  if (className.includes("assetType_genericMap")) return "map";
  if (className.includes("assetType_workoutRoute")) return "workoutRoute";
  if (className.includes("assetType_link")) return "link";
  if (className.includes("assetType_stateOfMind")) return "stateOfMind";
  if (className.includes("assetType_motionActivity")) return "motionActivity";
  if (className.includes("assetType_workoutIcon")) return "workoutIcon";
  if (className.includes("assetType_contact")) return "contact";
  return "unknown";
}
function extractAsset(item) {
  var _a, _b, _c, _d, _e, _f, _g, _h, _i, _j, _k, _l, _m, _n, _o, _p, _q, _r, _s, _t, _u, _v, _w, _x, _y;
  const uuid = (_a = item.id) != null ? _a : "";
  const type = classToAssetType(item.className);
  const rawSrc = (_m = (_l = (_j = (_h = (_f = (_d = (_b = item.querySelector("img.asset_image")) == null ? void 0 : _b.getAttribute("src")) != null ? _d : (_c = item.querySelector("img")) == null ? void 0 : _c.getAttribute("src")) != null ? _f : (_e = item.querySelector("video source")) == null ? void 0 : _e.getAttribute("src")) != null ? _h : (_g = item.querySelector("video")) == null ? void 0 : _g.getAttribute("src")) != null ? _j : (_i = item.querySelector("audio source")) == null ? void 0 : _i.getAttribute("src")) != null ? _l : (_k = item.querySelector("audio")) == null ? void 0 : _k.getAttribute("src")) != null ? _m : "";
  const stripped = rawSrc.replace(/^\.\.\/Resources\//, "").replace(/^Resources\//, "");
  let filename;
  try {
    filename = decodeURIComponent(stripped);
  } catch (e) {
    filename = stripped;
  }
  const overlayHeader = (_o = (_n = item.querySelector(".gridItemOverlayHeader")) == null ? void 0 : _n.textContent) == null ? void 0 : _o.trim();
  const overlayFooter = (_q = (_p = item.querySelector(".gridItemOverlayFooter")) == null ? void 0 : _p.textContent) == null ? void 0 : _q.trim();
  const activityType = (_s = (_r = item.querySelector(".activityType")) == null ? void 0 : _r.textContent) == null ? void 0 : _s.trim();
  const activityMetrics = (_u = (_t = item.querySelector(".activityMetrics")) == null ? void 0 : _t.textContent) == null ? void 0 : _u.trim();
  const overlayText = [overlayHeader, overlayFooter].filter(Boolean).join(" \xB7 ") || [activityType, activityMetrics].filter(Boolean).join(" \xB7 ") || void 0;
  const duration = ((_w = (_v = item.querySelector(".durationText")) == null ? void 0 : _v.textContent) == null ? void 0 : _w.trim()) || void 0;
  const href = (type === "link" ? (_y = (_x = item.querySelector("a")) == null ? void 0 : _x.getAttribute("href")) == null ? void 0 : _y.trim() : void 0) || void 0;
  const rawTypeClass = type === "unknown" ? item.className.trim() : void 0;
  if (!uuid && !filename) return void 0;
  return { uuid, type, filename, overlayText, duration, href, rawTypeClass };
}
function extractAssets(assetGrid) {
  const assets = [];
  const gridItems = Array.from(assetGrid.querySelectorAll(".gridItem"));
  if (gridItems.length === 0) {
    const single = extractAsset(assetGrid);
    if (single) assets.push(single);
    return assets;
  }
  for (const item of gridItems) {
    const asset = extractAsset(item);
    if (asset) assets.push(asset);
  }
  return assets;
}
function extractBodyLines(bodyEl) {
  const lines = [];
  function walk(el) {
    var _a, _b, _c, _d;
    const tag = el.tagName.toLowerCase();
    if (tag === "ul" || tag === "ol") {
      for (const li of Array.from(el.querySelectorAll(":scope > li"))) {
        const text = (_b = (_a = li.textContent) == null ? void 0 : _a.trim()) != null ? _b : "";
        if (text) lines.push(`- ${text}`);
      }
      return;
    }
    if (tag === "p" || tag === "div") {
      const childTags = Array.from(el.children).map(
        (c) => c.tagName.toLowerCase()
      );
      const hasBlockChildren = childTags.some(
        (t) => ["p", "div", "ul", "ol", "li"].includes(t)
      );
      if (!hasBlockChildren) {
        const text = (_d = (_c = el.textContent) == null ? void 0 : _c.trim()) != null ? _d : "";
        if (text) lines.push(text);
        return;
      }
    }
    for (const child of Array.from(el.children)) {
      walk(child);
    }
  }
  walk(bodyEl);
  return lines.filter((line, i, arr) => {
    if (line !== "") return true;
    return i > 0 && arr[i - 1] !== "";
  });
}
function parseHtmlEntry(htmlContent, sourcePath, filename) {
  var _a, _b, _c;
  const { date, titleFromFilename, duplicateSuffix } = parseEntryFilename(filename);
  const parser = new DOMParser();
  const doc = parser.parseFromString(htmlContent, "text/html");
  const htmlTitle = (_c = (_b = (_a = doc.querySelector(".title")) == null ? void 0 : _a.textContent) == null ? void 0 : _b.trim()) != null ? _c : "";
  const title = htmlTitle || titleFromFilename;
  const assets = [];
  for (const grid of Array.from(doc.querySelectorAll(".assetGrid"))) {
    assets.push(...extractAssets(grid));
  }
  const bodyEl = doc.querySelector(".bodyText");
  const bodyLines = bodyEl ? extractBodyLines(bodyEl) : [];
  return { date, title, assets, bodyLines, sourcePath, duplicateSuffix };
}

// src/converter.ts
function displayNameFor(filename, convertImages) {
  if (!convertImages) return filename;
  const dot = filename.lastIndexOf(".");
  if (dot === -1) return filename;
  const ext = filename.slice(dot).toLowerCase();
  return CONVERTED_IMAGE_EXTS.has(ext) ? filename.slice(0, dot) + ".jpg" : filename;
}
function safeMarkdownUrl(href) {
  if (!/^https?:\/\//i.test(href)) return void 0;
  return href.replace(/[\s()<>[\]]/g, (c) => {
    return "%" + c.charCodeAt(0).toString(16).toUpperCase().padStart(2, "0");
  });
}
function unknownTypeWarning(asset) {
  const label = asset.rawTypeClass ? `\`${asset.rawTypeClass}\`` : "unrecognized type";
  return `\u26A0\uFE0F Unrecognized asset type (${label}) \u2014 may need a plugin update`;
}
function assetToMarkdown(asset, convertImages) {
  const raw = asset.filename;
  if (!raw) return assetFallback(asset);
  const displayName = displayNameFor(raw, convertImages);
  switch (asset.type) {
    case "photo":
      return `![[${displayName}]]`;
    case "video":
      return `![[${displayName}]]`;
    case "audio":
      return `![[${displayName}]]`;
    case "music":
      return `![[${displayName}]]`;
    case "map": {
      const img = `![[${displayName}]]`;
      return asset.overlayText ? `\u{1F4CD} ${asset.overlayText}
${img}` : img;
    }
    case "workoutRoute": {
      const img = `![[${displayName}]]`;
      return asset.overlayText ? `\u{1F3C3} ${asset.overlayText}
${img}` : img;
    }
    case "link": {
      const img = `![[${displayName}]]`;
      const url = asset.href ? safeMarkdownUrl(asset.href) : void 0;
      return url ? `${img}
[\u{1F517} Link](${url})` : img;
    }
    case "stateOfMind": {
      const img = `![[${displayName}]]`;
      return asset.overlayText ? `\u{1F9E0} ${asset.overlayText}
${img}` : img;
    }
    case "motionActivity": {
      const img = `![[${displayName}]]`;
      return asset.overlayText ? `\u{1F3C3} ${asset.overlayText}
${img}` : img;
    }
    case "workoutIcon": {
      const img = `![[${displayName}]]`;
      return asset.overlayText ? `\u{1F4AA} ${asset.overlayText}
${img}` : img;
    }
    case "contact": {
      const img = `![[${displayName}]]`;
      return asset.overlayText ? `\u{1F464} ${asset.overlayText}
${img}` : img;
    }
    case "unknown": {
      const img = `![[${displayName}]]`;
      return `${img}
${unknownTypeWarning(asset)}`;
    }
    default:
      return assetFallback(asset);
  }
}
function assetFallback(asset) {
  switch (asset.type) {
    case "stateOfMind":
      return "\u{1F9E0} State of mind";
    case "motionActivity":
      return "\u{1F3C3} Activity recorded";
    case "workoutIcon":
      return "\u{1F4AA} Workout";
    case "contact":
      return "\u{1F464} Contact";
    case "music":
      return "\u{1F3B5} Music";
    case "workoutRoute":
      return "\u{1F3C3} Workout route";
    case "link": {
      const url = asset.href ? safeMarkdownUrl(asset.href) : void 0;
      return url ? `[\u{1F517} Link](${url})` : "\u{1F517} Link";
    }
    case "unknown":
      return unknownTypeWarning(asset);
    default:
      return "";
  }
}
function entryToMarkdown(entry, _mediaSubfolder, convertImages) {
  const lines = [];
  lines.push("---");
  lines.push(`date: ${entry.date}`);
  if (entry.title) {
    lines.push(`title: "${entry.title.replace(/"/g, '\\"')}"`);
  }
  lines.push("tags:");
  lines.push("  - journal");
  lines.push("---");
  lines.push("");
  for (const asset of entry.assets) {
    const md = assetToMarkdown(asset, convertImages);
    if (md) {
      lines.push(md);
      lines.push("");
    }
  }
  if (entry.bodyLines.length > 0) {
    lines.push(...entry.bodyLines);
    lines.push("");
  }
  return lines.join("\n");
}

// src/importer.ts
var execFileAsync = (0, import_util.promisify)(import_child_process.execFile);
function sanitiseName(name) {
  return name.replace(/[\\/:*?"<>|#^[\]]/g, "-").trim();
}
function vaultBasePath(app) {
  return app.vault.adapter.getBasePath();
}
async function ensureVaultFolder(app, vaultPath) {
  if (!app.vault.getAbstractFileByPath(vaultPath)) {
    await app.vault.createFolder(vaultPath);
  }
}
async function writeNote(app, vaultPath, content) {
  const existing = app.vault.getAbstractFileByPath(vaultPath);
  if (existing instanceof import_obsidian.TFile) {
    await app.vault.modify(existing, content);
  } else {
    await app.vault.create(vaultPath, content);
  }
}
var IMAGE_EXTS = CONVERTED_IMAGE_EXTS;
async function copyMedia(srcPath, destAbsPath, convertHeic) {
  if (fs.existsSync(destAbsPath)) return;
  const ext = path.extname(srcPath).toLowerCase();
  if (IMAGE_EXTS.has(ext) && convertHeic) {
    await execFileAsync("sips", [
      "-s",
      "format",
      "jpeg",
      srcPath,
      "--out",
      destAbsPath
    ]);
  } else {
    await fsp.copyFile(srcPath, destAbsPath);
  }
}
async function processAssets(assets, resourcesDir, mediaFolderAbsPath, convertHeic) {
  await fsp.mkdir(mediaFolderAbsPath, { recursive: true });
  const stats = { missing: [], failed: [] };
  for (const asset of assets) {
    if (!asset.filename) continue;
    const srcPath = path.join(resourcesDir, asset.filename);
    if (!fs.existsSync(srcPath)) {
      stats.missing.push(asset.filename);
      continue;
    }
    const rawExt = path.extname(asset.filename);
    const ext = rawExt.toLowerCase();
    const destFilename = IMAGE_EXTS.has(ext) && convertHeic ? asset.filename.slice(0, asset.filename.length - rawExt.length) + ".jpg" : asset.filename;
    const destAbsPath = path.join(mediaFolderAbsPath, destFilename);
    try {
      await copyMedia(srcPath, destAbsPath, convertHeic);
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      stats.failed.push({ file: asset.filename, error: message });
      try {
        await fsp.rm(destAbsPath, { force: true });
        await fsp.copyFile(srcPath, destAbsPath);
      } catch (e) {
      }
    }
  }
  return stats;
}
function resolveEntryPaths(entry, targetFolder, mediaSubfolder) {
  const date = entry.date || "unknown";
  const dayFolder = (0, import_obsidian.normalizePath)(`${targetFolder}/${sanitiseName(date)}`);
  let noteBaseName;
  if (entry.duplicateSuffix) {
    noteBaseName = `${date} ${entry.duplicateSuffix}`;
  } else if (entry.title) {
    noteBaseName = `${date} - ${sanitiseName(entry.title)}`;
  } else {
    noteBaseName = date;
  }
  const noteFile = (0, import_obsidian.normalizePath)(`${dayFolder}/${noteBaseName}.md`);
  const mediaFolder = (0, import_obsidian.normalizePath)(`${dayFolder}/${mediaSubfolder}`);
  return { dayFolder, noteFile, mediaFolder };
}
async function runImport(app, settings, exportPath, onProgress) {
  var _a;
  const entriesDir = path.join(exportPath, "Entries");
  const resourcesDir = path.join(exportPath, "Resources");
  const htmlFiles = fs.readdirSync(entriesDir).filter((f) => f.toLowerCase().endsWith(".html")).sort();
  const result = {
    total: htmlFiles.length,
    imported: 0,
    skipped: 0,
    errors: [],
    mediaMissing: [],
    mediaErrors: [],
    unrecognizedAssetTypes: []
  };
  await ensureVaultFolder(app, settings.targetFolder);
  const basePath = vaultBasePath(app);
  for (let i = 0; i < htmlFiles.length; i++) {
    const filename = htmlFiles[i];
    onProgress(i + 1, htmlFiles.length, filename);
    try {
      const htmlPath = path.join(entriesDir, filename);
      const htmlContent = await fsp.readFile(htmlPath, "utf-8");
      const entry = parseHtmlEntry(htmlContent, htmlPath, filename);
      for (const asset of entry.assets) {
        if (asset.type === "unknown") {
          result.unrecognizedAssetTypes.push({
            entry: filename,
            file: asset.filename || asset.uuid,
            className: (_a = asset.rawTypeClass) != null ? _a : "(no class)"
          });
        }
      }
      const { dayFolder, noteFile, mediaFolder } = resolveEntryPaths(
        entry,
        settings.targetFolder,
        settings.mediaSubfolder
      );
      await ensureVaultFolder(app, dayFolder);
      if (entry.assets.some((a) => a.filename)) {
        const mediaFolderAbs = path.join(basePath, mediaFolder);
        const mediaStats = await processAssets(
          entry.assets,
          resourcesDir,
          mediaFolderAbs,
          settings.convertHeic
        );
        for (const file of mediaStats.missing) {
          result.mediaMissing.push({ entry: filename, file });
        }
        for (const failure of mediaStats.failed) {
          result.mediaErrors.push({ entry: filename, ...failure });
        }
      }
      const markdown = entryToMarkdown(
        entry,
        settings.mediaSubfolder,
        settings.convertHeic
      );
      await writeNote(app, noteFile, markdown);
      result.imported++;
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      result.errors.push({ entry: filename, error: message });
    }
  }
  return result;
}
function validateExportPath(exportPath) {
  if (!exportPath) return "Please enter the path to your Apple Journal export folder.";
  const trimmed = exportPath.trim();
  if (!fs.existsSync(trimmed)) return `Folder not found: ${trimmed}`;
  const entriesDir = path.join(trimmed, "Entries");
  const resourcesDir = path.join(trimmed, "Resources");
  if (!fs.existsSync(entriesDir))
    return `Could not find an Entries/ subfolder inside:
${trimmed}`;
  if (!fs.existsSync(resourcesDir))
    return `Could not find a Resources/ subfolder inside:
${trimmed}`;
  const count = fs.readdirSync(entriesDir).filter((f) => f.toLowerCase().endsWith(".html")).length;
  if (count === 0) return "No .html entry files found in the Entries/ folder.";
  return null;
}
function countEntries(exportPath) {
  const entriesDir = path.join(exportPath.trim(), "Entries");
  return fs.readdirSync(entriesDir).filter((f) => f.toLowerCase().endsWith(".html")).length;
}

// src/ui/ImportModal.ts
var ImportModal = class extends import_obsidian2.Modal {
  constructor(app, settings) {
    super(app);
    this.settings = settings;
    this.exportPath = "";
    this.modalEl.addClass("apple-journal-importer-modal");
  }
  onOpen() {
    this.renderPicker();
  }
  onClose() {
    this.contentEl.empty();
  }
  // ---------------------------------------------------------------------------
  // Step 1 — path picker
  // ---------------------------------------------------------------------------
  renderPicker() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Import Apple Journal" });
    contentEl.createEl("p", {
      text: "Point to the folder you exported from the Apple Journal app. It should contain an Entries/ and a Resources/ subfolder.",
      cls: "setting-item-description"
    });
    const pathSetting = new import_obsidian2.Setting(contentEl).setName("Export folder path").setClass("path-setting").addText((text) => {
      text.setPlaceholder("/Users/you/Downloads/AppleJournalEntries").setValue(this.exportPath).onChange((val) => {
        this.exportPath = val;
      });
      text.inputEl.addClass("apple-journal-path-input");
      text.inputEl.addEventListener("keydown", (e) => {
        if (e.key === "Enter") this.confirmPath();
      });
    });
    pathSetting.settingEl.addClass("apple-journal-path-setting");
    new import_obsidian2.Setting(contentEl).addButton((btn) => {
      btn.setButtonText("Next \u2192").setCta().onClick(() => this.confirmPath());
    });
  }
  confirmPath() {
    const path2 = this.exportPath.trim();
    const error = validateExportPath(path2);
    if (error) {
      new import_obsidian2.Notice(error);
      return;
    }
    this.renderConfirm(path2);
  }
  // ---------------------------------------------------------------------------
  // Step 2 — confirm + start
  // ---------------------------------------------------------------------------
  renderConfirm(exportPath) {
    const { contentEl } = this;
    contentEl.empty();
    const count = countEntries(exportPath);
    contentEl.createEl("h2", { text: "Ready to import" });
    contentEl.createEl("p", {
      text: `Found ${count} journal entries.`
    });
    contentEl.createEl("p", {
      text: `They will be imported into "${this.settings.targetFolder}" in your vault.`,
      cls: "setting-item-description"
    });
    if (this.settings.convertHeic) {
      contentEl.createEl("p", {
        text: "HEIC images will be converted to JPEG (requires macOS).",
        cls: "setting-item-description"
      });
    }
    new import_obsidian2.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("\u2190 Back").onClick(() => this.renderPicker())
    ).addButton((btn) => {
      btn.setButtonText(`Import ${count} entries`).setCta().onClick(() => this.startImport(exportPath, count));
    });
  }
  // ---------------------------------------------------------------------------
  // Step 3 — progress
  // ---------------------------------------------------------------------------
  async startImport(exportPath, total) {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Importing\u2026" });
    const progressWrap = contentEl.createDiv({ cls: "progress-wrap" });
    const progressBar = progressWrap.createEl("progress");
    progressBar.max = total;
    progressBar.value = 0;
    const progressLabel = progressWrap.createDiv({
      cls: "progress-label",
      text: "Starting\u2026"
    });
    const result = await runImport(
      this.app,
      this.settings,
      exportPath,
      (current, _total, label) => {
        progressBar.value = current;
        progressLabel.setText(`${current} / ${_total} \u2014 ${label}`);
      }
    );
    this.renderSummary(result);
  }
  // ---------------------------------------------------------------------------
  // Step 4 — summary
  // ---------------------------------------------------------------------------
  renderSummary(result) {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Import complete" });
    const stats = contentEl.createDiv({ cls: "summary-stats" });
    this.createStat(stats, String(result.imported), "imported");
    if (result.skipped > 0) {
      this.createStat(stats, String(result.skipped), "skipped");
    }
    if (result.errors.length > 0) {
      this.createStat(stats, String(result.errors.length), "errors", true);
    }
    if (result.mediaMissing.length > 0) {
      this.createStat(
        stats,
        String(result.mediaMissing.length),
        "media missing",
        true
      );
    }
    if (result.mediaErrors.length > 0) {
      this.createStat(
        stats,
        String(result.mediaErrors.length),
        "media errors",
        true
      );
    }
    if (result.unrecognizedAssetTypes.length > 0) {
      this.createStat(
        stats,
        String(result.unrecognizedAssetTypes.length),
        "unrecognized asset types",
        true
      );
    }
    if (result.errors.length > 0) {
      contentEl.createEl("p", { text: "Errors:" });
      const log = contentEl.createDiv({ cls: "error-log" });
      for (const err of result.errors) {
        log.createEl("p", { text: `${err.entry}: ${err.error}` });
      }
    }
    const mediaProblems = [
      ...result.mediaMissing.map(
        (m) => `${m.entry}: ${m.file} not found in the export's Resources/`
      ),
      ...result.mediaErrors.map(
        (m) => `${m.entry}: ${m.file} \u2014 ${m.error.split("\n")[0]}`
      )
    ];
    if (mediaProblems.length > 0) {
      contentEl.createEl("p", { text: "Media problems:" });
      const log = contentEl.createDiv({ cls: "error-log" });
      for (const line of mediaProblems) {
        log.createEl("p", { text: line });
      }
    }
    if (result.unrecognizedAssetTypes.length > 0) {
      contentEl.createEl("p", {
        text: "Unrecognized asset types (flagged in the note; embedded when a media file was found):"
      });
      const log = contentEl.createDiv({ cls: "error-log" });
      for (const u of result.unrecognizedAssetTypes) {
        log.createEl("p", { text: `${u.entry}: ${u.file} \u2014 ${u.className}` });
      }
    }
    new import_obsidian2.Setting(contentEl).addButton((btn) => {
      btn.setButtonText("Close").setCta().onClick(() => this.close());
    });
  }
  createStat(parent, value, label, isError = false) {
    const stat = parent.createDiv({ cls: "stat" });
    const valueEl = stat.createDiv({ cls: "stat-value", text: value });
    if (isError) valueEl.addClass("error");
    stat.createDiv({ cls: "stat-label", text: label });
  }
};

// src/ui/SettingsTab.ts
var import_obsidian3 = require("obsidian");
var SettingsTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian3.Setting(containerEl).setName("Target folder").setDesc(
      "Vault folder where imported entries will be created. Will be created if it does not exist."
    ).addText((text) => {
      text.setPlaceholder("Journal").setValue(this.plugin.settings.targetFolder).onChange(async (val) => {
        this.plugin.settings.targetFolder = val.trim() || "Journal";
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian3.Setting(containerEl).setName("Convert HEIC to JPEG").setDesc(
      "Convert Apple HEIC images to JPEG so Obsidian can display them inline. Uses the built-in macOS sips command."
    ).addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.convertHeic).onChange(async (val) => {
        this.plugin.settings.convertHeic = val;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian3.Setting(containerEl).setName("Media subfolder name").setDesc(
      "Name of the subfolder inside each entry folder where media files are stored."
    ).addText((text) => {
      text.setPlaceholder("media").setValue(this.plugin.settings.mediaSubfolder).onChange(async (val) => {
        this.plugin.settings.mediaSubfolder = val.trim() || "media";
        await this.plugin.saveSettings();
      });
    });
  }
};

// src/main.ts
var AppleJournalImporterPlugin = class extends import_obsidian4.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new SettingsTab(this.app, this));
    this.addCommand({
      id: "import-apple-journal",
      name: "Import Apple Journal",
      callback: () => new ImportModal(this.app, this.settings).open()
    });
    this.addCommand({
      id: "new-journal-entry",
      name: "New journal entry for today",
      callback: () => this.createTodayEntry()
    });
    this.addRibbonIcon("book-open", "Import Apple Journal", () => {
      new ImportModal(this.app, this.settings).open();
    });
  }
  async createTodayEntry() {
    const today = /* @__PURE__ */ new Date();
    const date = [
      today.getFullYear(),
      String(today.getMonth() + 1).padStart(2, "0"),
      String(today.getDate()).padStart(2, "0")
    ].join("-");
    const dayFolder = (0, import_obsidian4.normalizePath)(`${this.settings.targetFolder}/${date}`);
    const mediaFolder = (0, import_obsidian4.normalizePath)(`${dayFolder}/${this.settings.mediaSubfolder}`);
    const notePath = (0, import_obsidian4.normalizePath)(`${dayFolder}/${date}.md`);
    for (const folder of [this.settings.targetFolder, dayFolder, mediaFolder]) {
      if (!this.app.vault.getAbstractFileByPath(folder)) {
        await this.app.vault.createFolder(folder);
      }
    }
    let file = this.app.vault.getAbstractFileByPath(notePath);
    if (!(file instanceof import_obsidian4.TFile)) {
      const content = `---
date: ${date}
tags:
  - journal
---

`;
      file = await this.app.vault.create(notePath, content);
    }
    if (file instanceof import_obsidian4.TFile) {
      await this.app.workspace.getLeaf(false).openFile(file);
    }
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
